---
default:
  image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm

stages:
  - build
  - test
  - deploy

build-python-package:
  stage: build
  before_script:
    - pip install uv
  script:
    - tools/build-package.sh
  artifacts:
    paths:
      - 'dist/*.whl'
    expire_in: 1 week

build-documentation:
  stage: build
  before_script:
    - pip install uv
  script:
    - tools/build-docs.sh
  artifacts:
    paths:
      - build/html/

test-python-package:
  stage: test
  before_script:
    - pip install uv
  script:
    - tools/test-package.sh
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

lint-python-package:
  stage: test
  before_script:
    # TODO: Add flake8-gl-codeclimate as dependency
    - pip install flake8-gl-codeclimate
    - pip install uv
  script:
    - uv run --all-extras flake8 src/python_training_project --format gl-codeclimate --output-file gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

deploy-python-package:
  stage: deploy
  before_script:
    - pip install uv
  variables:
    UV_PUBLISH_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    UV_PUBLISH_USERNAME: gitlab-ci-token
    UV_PUBLISH_PASSWORD: ${CI_JOB_TOKEN}

  script:
    - tools/deploy-package.sh

pages:
  stage: deploy
  script:
    - mv build/html/ public/
  artifacts:
    paths:
      - public/
    