---
default:
  image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm

stages:
  - build
  - test
  - deploy

include:
  - template: Jobs/Code-Quality.gitlab-ci.yml

build-python-package:
  stage: build
  before_script:
    - pip install uv
  script:
    - tools/build-package.sh
  artifacts:
    paths:
      - 'dist/*.whl'
    expire_in: 1 week

build-documentation:
  stage: build
  before_script:
    - pip install uv
  script:
    - tools/build-docs.sh

code_quality:
  when: manual

test-python-package:
  stage: test
  before_script:
    - pip install uv
  script:
    - tools/test-package.sh
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

deploy-python-package:
  stage: deploy
  before_script:
    - pip install uv
  script:
    - tools/deploy-package.sh
