FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye

# Install Debian packages
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     XXX \
#     && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*
